tasks:
  - name: Gitpod Task
    before: |
      echo "Retrieving the last part of the Workspace Context URL ..."
      path=$(gp info | awk -F'/' '/Workspace Context URL/{print $NF}' | tr -d '[:space:]')
      echo "Path '$path' is set."

      echo "Prepare for for '$path' ..."
      case "$path" in
        "magento-backend")
          echo "Build magento-backend application"
          cd magento-backend
        ;;
        "vue-frontend")
          echo "Build vue-frontend application"
          cd vue-frontend && npm install
        ;;
      esac
      
    command: |
        case "$path" in
          "magento-backend")
            export APP_URL=`gp url 8080 | sed 's~https://~~'`
            docker-compose up
          ;;
          "vue-frontend")
            # Check if environment variables are set in https://gitpod.io/variables.
            echo "Checking if environment variables are set ..."
            if [ -z ${baseUrl+x} ] || [[ -z ${bearerToken+x} ]] || [[ -z ${ADYEN_CLIENT_KEY+x} ]]; then
              echo "Expected environment variables not found. Please set the bearerToken, baseUrl, ADYEN_CLIENT_KEY environment variables and rerun session https://gitpod.io/variables."
              exit 1
            else
              cp .env.example .env
              sed -i~ "s|.*baseUrl=*|baseUrl=$baseUrl|" .env
              sed -i~ "s|.*bearerToken=*|bearerToken=$bearerToken|" .env
              sed -i~ "s|.*ADYEN_CLIENT_KEY=*|ADYEN_CLIENT_KEY=$ADYEN_CLIENT_KEY|" .env
            fi

            # Run the application based on specified $path.
            echo "Starting application for '$path' in $(pwd)"
            npm run dev
          ;;
        esac

ports:
- port: 8080
  onOpen: open-preview
  visibility: public

vscode:
  extensions:
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - ms-azuretools.vscode-docker
